---

- name: Install
  become: true
  apt:
    name: ufw
    update_cache: yes

- name: Allow ssh
  become: true
  ufw:
    rule: limit
    port: '22'
    proto: tcp

- name: Expose proxy http
  become: true
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Expose proxy https
  become: true
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Expose apm-server
  become: true
  ufw:
    rule: allow
    port: '8200'
    proto: tcp

- name: Enable
  become: true
  ufw:
    state: enabled
